import Head from "next/head";
import { About } from "../components/About";
import { Navbar } from "../components/Navbar";
import { Team } from "../components/Team";
import { WhatWeDo } from "../components/WhatWeDo";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="overflow-hidden h-full flex flex-col">
        <Navbar></Navbar>
        <About></About>
        <Team></Team>
        <WhatWeDo></WhatWeDo>
      </main>
    </div>
  );
}
