import Head from "next/head";
import { About } from "../components/About";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-screen overflow-hidden h-full">
        <About></About>
      </main>
    </div>
  );
}
